"""Offline verification of Render/Neon setup and DB adapter.

The actual hosted PostgreSQL credentials are user-controlled; these tests do
not pretend that a remote database or Panta service has been exercised.
"""
import os
import unittest
from pathlib import Path
from unittest.mock import patch
from app import postgres, storage

ROOT=Path(__file__).resolve().parents[1]

class FakePG:
    def __init__(self): self.statements=[]
    def execute(self,query,parameters=()):
        self.statements.append((query,parameters))
        return self
    def commit(self): pass
    def rollback(self): pass
    def close(self): pass

class DeploymentTests(unittest.TestCase):
    def test_qmark_translation_respects_literals(self):
        q="SELECT * FROM audit WHERE event=? AND detail='a?b' AND created_at=? AND description=\"?\""
        result=postgres.rewrite_parameters(q)
        self.assertIn('event=%s',result)
        self.assertIn("'a?b'",result)
        self.assertIn('created_at=%s',result)
        self.assertIn('description="?"',result)
    def test_postgres_adapter_parameterizes_values(self):
        fake=FakePG(); conn=postgres.Connection(fake)
        conn.execute('SELECT * FROM users WHERE email=?',('a@example.com',))
        self.assertEqual(fake.statements[0],('SELECT * FROM users WHERE email=%s',('a@example.com',)))
    def test_postgres_schema_identity_columns_and_indexes(self):
        fake=FakePG(); postgres.Connection(fake).executescript(storage.DDL)
        statements=[s for s,_ in fake.statements]
        self.assertEqual(sum('CREATE TABLE' in s for s in statements),13)
        self.assertTrue(all('id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' in st for st in statements if st.startswith('CREATE TABLE') and '(id ' in st))
        self.assertGreaterEqual(sum('CREATE INDEX' in st for st in statements),3)
        self.assertTrue(any('public_reports' in st for st in statements))
    def test_require_durable_db_refuses_ephemeral_storage(self):
        with patch.dict(os.environ,{'OUTCOMEOS_REQUIRE_POSTGRES':'1','DATABASE_URL':''}):
            with self.assertRaisesRegex(RuntimeError, 'DATABASE_URL is required'):
                storage.connect()
    def test_manifest_never_commits_deployment_secrets(self):
        yml=(ROOT/'render.yaml').read_text()
        self.assertIn('plan: free',yml)
        self.assertIn('DATABASE_URL\n        sync: false',yml)
        self.assertIn('PANTA_API_KEY\n        sync: false',yml)
        self.assertIn('OUTCOMEOS_REQUIRE_POSTGRES',yml)
        self.assertIn('OUTCOMEOS_COOKIE_SECURE',yml)
        self.assertIn('OUTCOMEOS_SEED_EXAMPLES',yml)
    def test_landing_and_sanitized_sample(self):
        text=(ROOT/'web'/'landing.html').read_text()
        self.assertIn('Illustrative product workflow',text)
        self.assertIn('href="/app"',text)
        self.assertIn('Actual quotes are retrieved from Panta API',text)
    def test_no_user_exposed_key_in_bundle(self):
        # Scan for any hardcoded live secret, rather than comparing against its value.
        files=[*ROOT.glob('app/*.py'),*ROOT.glob('web/*'),*ROOT.glob('docs/*.md'),ROOT/'render.yaml',ROOT/'README.md']
        for file in files:
            self.assertNotRegex(file.read_text(),r'pk_live_[A-Za-z0-9_-]{12,}',msg=str(file))

if __name__=='__main__':unittest.main()
