"""PostgreSQL backend for durable public hosting.

The rest of OutcomeOS intentionally uses portable '?' parameter markers and
SQLite-compatible rows. This module adapts them to psycopg3's '%s' and dict rows.
All SQL fragments are static application strings; user input remains parameters.
"""
from __future__ import annotations
import re


def rewrite_parameters(sql: str) -> str:
    """Convert qmark placeholders outside SQL string literals to psycopg style."""
    output = []
    state = None
    index = 0
    while index < len(sql):
        char = sql[index]
        if state:
            output.append(char)
            if char == state:
                if index + 1 < len(sql) and sql[index + 1] == state:
                    output.append(sql[index + 1])
                    index += 1
                else:
                    state = None
        elif char in ("'", '"'):
            output.append(char)
            state = char
        elif char == '?':
            output.append('%s')
        else:
            output.append(char)
        index += 1
    return ''.join(output)


def postgres_ddl(sqlite_ddl: str) -> list[str]:
    """Translate static SQLite table definitions into PostgreSQL-compatible DDL."""
    tables = []
    for statement in sqlite_ddl.split(';'):
        statement = statement.strip()
        if not statement:
            continue
        statement = re.sub(r'\bid INTEGER PRIMARY KEY\b',
                           'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
                           statement)
        # SQLite REAL stores a double; PostgreSQL REAL is only 32-bit.
        # Preserve quote precision for change detection and scoring.
        statement = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', statement)
        tables.append(statement)
    return tables


class Connection:
    def __init__(self, connection):
        self._connection = connection

    def execute(self, query, params=()):
        return self._connection.execute(rewrite_parameters(query), params)

    def executescript(self, ddl):
        for statement in postgres_ddl(ddl):
            self.execute(statement)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def connect(url: str):
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError('PostgreSQL requires: pip install -r requirements-cloud.txt') from exc
    if not url.startswith(('postgresql://', 'postgres://')):
        raise RuntimeError('DATABASE_URL must be a PostgreSQL connection URL')
    # Use certificate verification for a managed remote service. Neon provides
    # TLS by default; an explicit sslmode in a user's URL is respected.
    from urllib.parse import urlsplit, parse_qs
    parsed = urlsplit(url)
    sslmode = parse_qs(parsed.query).get('sslmode', ['require'])[-1]
    if sslmode not in ('require', 'verify-ca', 'verify-full'):
        raise RuntimeError('DATABASE_URL must enable TLS (sslmode=require or stricter)')
    params = {'row_factory': dict_row, 'connect_timeout': 12, 'sslmode': sslmode}
    return Connection(psycopg.connect(url, **params))
